version: '3.8'
services:
  postgres-1:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Events
    networks:
      - my_network
    ports:
      - "5432:5432"

  myapp:
    build: .
    depends_on:
      - postgres-1
    environment:
      DB_HOST: postgres-1
      DB_NAME: Events
      DB_USER: postgres
      DB_PASSWORD: admin
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
